"""End-to-end: every file in sample-logs/detection goes through the real
/upload pipeline (parser -> normalizer -> 28 rules -> cooldown -> storage)
and must raise exactly the detections it was written to demonstrate.

Samples are regenerated by sample-logs/detection/generate_samples.py. All
uploads in one test share the rolled-back database transaction, so
cross-upload state (baselines, heartbeats, feeds) behaves as in production.
Pre-existing dev-database history is neutralised inside that transaction so
earlier manual uploads of the same samples can't suppress or seed results.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from io import BytesIO
from pathlib import Path
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import delete, select, update

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.main import app
from app.models.alert import Alert
from app.models.detection_rule_setting import DetectionRuleSetting
from app.models.entity_baseline import EntityBaseline
from app.models.host_heartbeat import HostHeartbeat
from app.models.role import Role
from app.models.threat_indicator import ThreatIndicator
from app.models.user import User
from app.security import current_user

SAMPLES = Path(__file__).resolve().parents[2] / "sample-logs" / "detection"
client = TestClient(app)

GROUP_A = {
    "new_account_created", "privileged_group_modified", "cron_persistence",
    "security_control_disabled", "log_tampering", "ssh_key_added", "host_log_silence",
}
GROUP_B = {
    "direct_root_login", "service_account_interactive", "login_to_nonexistent_account",
    "off_hours_login", "dormant_account_activity", "impossible_travel", "first_seen_geo_asn",
}
GROUP_C = {
    "lateral_movement_chain", "host_sweep", "outbound_beaconing", "dns_tunneling",
    "egress_volume_anomaly", "threat_intel_match",
}


@pytest.fixture(autouse=True)
def isolated_admin(db_session):
    admin_role = db_session.scalar(select(Role).where(Role.name == "Admin"))
    if admin_role is None:
        admin_role = Role(name="Admin", description="Administrator")
        db_session.add(admin_role)
        db_session.flush()
    suffix = uuid4().hex
    admin = User(
        role_id=admin_role.id,
        username=f"samples_admin_{suffix}",
        email=f"samples_admin_{suffix}@example.test",
        password_hash="not-used",
        is_active=True,
    )
    db_session.add(admin)

    # Neutralise any committed history from manual runs — rolled back afterwards.
    db_session.execute(update(Alert).values(entity_id=None))
    for model in (EntityBaseline, HostHeartbeat, ThreatIndicator, DetectionRuleSetting):
        db_session.execute(delete(model))
    db_session.commit()

    app.dependency_overrides[current_user] = lambda: admin
    yield
    app.dependency_overrides.pop(current_user, None)


def upload(name: str) -> list[dict]:
    content = (SAMPLES / name).read_bytes()
    mime = "text/csv" if name.endswith(".csv") else "text/plain"
    response = client.post("/upload", files={"logfile": (name, BytesIO(content), mime)})
    assert response.status_code == 200, response.text
    return response.json()["alerts"]


def by_rule(alerts: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for alert in alerts:
        grouped[alert["rule"]].append(alert)
    return grouped


def configure_rosters() -> None:
    for rule, allowlist in (
        ("service_account_interactive", ["svc-backup"]),
        ("login_to_nonexistent_account", ["jsmith-old"]),
    ):
        response = client.patch(f"/detection/rules/{rule}", json={"allowlist": allowlist})
        assert response.status_code == 200, response.text


def import_feed() -> None:
    response = client.post(
        "/threat-intel/feeds",
        json={"source": "sample-feed", "content": (SAMPLES / "threat-intel-feed.txt").read_text()},
    )
    assert response.status_code == 200, response.text
    assert response.json()["imported"] == 3
    assert response.json()["rejected_lines"] == 1


# ── Group A ─────────────────────────────────────────────────────────────────

def test_group_a_host_integrity_sample_fires_every_host_rule():
    fired = by_rule(upload("group-a-host-integrity.log"))

    assert {
        "new_account_created", "privileged_group_modified", "cron_persistence",
        "security_control_disabled", "log_tampering", "ssh_key_added",
    } <= set(fired)
    assert fired["new_account_created"][0]["username"] == "support2"
    assert fired["new_account_created"][0]["mitre_technique"] == "T1136"
    reasons = " ".join(a["description"] for a in fired["security_control_disabled"])
    assert "firewall rules flushed" in reasons and "SELinux" in reasons
    tamper = " ".join(a["description"] for a in fired["log_tampering"])
    assert "auditd" in tamper and "history" in tamper
    assert fired["ssh_key_added"][0]["evidence"]["file_path"] == "/root/.ssh/authorized_keys"


def test_group_a_normal_admin_sample_is_quiet():
    fired = set(by_rule(upload("group-a-normal-admin.log")))
    assert not fired & GROUP_A, fired


def test_audit_log_sample_detects_key_write_but_not_sshd_read():
    fired = by_rule(upload("audit.log"))

    assert len(fired["ssh_key_added"]) == 1
    key_alert = fired["ssh_key_added"][0]
    assert key_alert["hostname"] == "app01"
    assert key_alert["username"] == "mallory"
    tamper = " ".join(a["description"] for a in fired["log_tampering"])
    assert "history" in tamper and "audit rules" in tamper
    assert any("MAC_STATUS" in a["description"] for a in fired["security_control_disabled"])
    assert not {"process", "exe"} - set(key_alert["evidence"])


def test_heartbeat_sample_detects_resumed_and_ongoing_silence():
    fired = by_rule(upload("group-a-heartbeat.log"))

    silent = {a["entity_id"]: a for a in fired["host_log_silence"]}
    assert set(silent) == {"db02", "cache01"}
    assert silent["db02"]["evidence"]["ongoing"] is False
    assert silent["cache01"]["evidence"]["ongoing"] is True

    hosts = {h["hostname"]: h for h in client.get("/detection/host-heartbeats").json()["hosts"]}
    assert {"web03", "db02", "cache01"} <= set(hosts)
    assert hosts["web03"]["event_count"] == 221

    # Re-uploading doesn't re-alert the same silence episode.
    assert "host_log_silence" not in by_rule(upload("group-a-heartbeat.log"))


# ── Group B ─────────────────────────────────────────────────────────────────

def test_group_b_identity_sample():
    configure_rosters()
    fired = by_rule(upload("group-b-identity.log"))

    assert fired["direct_root_login"][0]["username"] == "root"
    assert fired["service_account_interactive"][0]["username"] == "svc-backup"
    assert fired["login_to_nonexistent_account"][0]["username"] == "jsmith-old"
    assert [a["username"] for a in fired["off_hours_login"]] == ["dave"]
    assert [a["username"] for a in fired["lateral_movement_chain"]] == ["erin"]


def test_group_b_normal_logins_sample_is_quiet():
    configure_rosters()
    fired = set(by_rule(upload("group-b-normal-logins.log")))
    assert not fired & (GROUP_B | {"lateral_movement_chain"}), fired


def test_group_b_geo_sample():
    fired = by_rule(upload("group-b-geo-logins.csv"))

    assert [a["username"] for a in fired["impossible_travel"]] == ["carol"]
    travel = fired["impossible_travel"][0]["evidence"]
    assert travel["from_country"] == "US" and travel["to_country"] == "NL"
    assert travel["distance_km"] > 5000
    assert [a["username"] for a in fired["first_seen_geo_asn"]] == ["carol"]


def test_group_b_dormant_samples_across_two_uploads():
    assert "dormant_account_activity" not in by_rule(upload("group-b-dormant-part1.csv"))
    fired = by_rule(upload("group-b-dormant-part2.csv"))
    assert [a["username"] for a in fired["dormant_account_activity"]] == ["frank"]


# ── Group C ─────────────────────────────────────────────────────────────────

def test_group_c_firewall_sample():
    import_feed()
    fired = by_rule(upload("group-c-firewall.log"))

    assert [a["source_ip"] for a in fired["host_sweep"]] == ["203.0.113.77"]
    assert fired["host_sweep"][0]["evidence"]["destination_port"] == 22
    assert [a["source_ip"] for a in fired["port_scan"]] == ["198.51.100.200"]
    intel = fired["threat_intel_match"]
    assert [a["entity_id"] for a in intel] == ["10.0.2.44"]
    assert intel[0]["evidence"]["indicator"] == "185.220.101.45"
    assert "outbound_beaconing" not in fired


def test_group_c_netflow_sample():
    import_feed()
    fired = by_rule(upload("group-c-netflow.csv"))

    assert [a["entity_id"] for a in fired["outbound_beaconing"]] == ["ws-114"]
    assert fired["outbound_beaconing"][0]["evidence"]["jitter_percent"] < 15
    assert [a["entity_id"] for a in fired["egress_volume_anomaly"]] == ["fs-02"]
    assert [a["entity_id"] for a in fired["threat_intel_match"]] == ["ws-130"]
    assert fired["threat_intel_match"][0]["evidence"]["indicator"] == "45.155.205.0/24"


def test_group_c_dns_sample():
    import_feed()
    fired = by_rule(upload("group-c-dns.log"))

    assert [a["entity_id"] for a in fired["dns_tunneling"]] == ["10.0.5.23"]
    assert fired["dns_tunneling"][0]["evidence"]["parent_domain"] == "exfil-tunnel.net"
    intel = fired["threat_intel_match"]
    assert [a["entity_id"] for a in intel] == ["10.0.5.40"]
    assert intel[0]["evidence"]["indicator"] == "badactor-c2.com"


def test_threat_intel_rule_is_silent_without_an_imported_feed():
    assert "threat_intel_match" not in by_rule(upload("group-c-firewall.log"))


def test_all_samples_in_recommended_order_cover_every_group():
    """One continuous session, uploading everything as a user would."""

    configure_rosters()
    import_feed()
    fired: set[str] = set()
    for name in (
        "group-a-host-integrity.log", "group-a-normal-admin.log", "audit.log",
        "group-b-identity.log", "group-b-normal-logins.log", "group-b-geo-logins.csv",
        "group-b-dormant-part1.csv", "group-b-dormant-part2.csv",
        "group-c-firewall.log", "group-c-netflow.csv", "group-c-dns.log",
        "group-a-heartbeat.log",
    ):
        fired |= set(by_rule(upload(name)))

    assert GROUP_A | GROUP_B | GROUP_C <= fired, sorted((GROUP_A | GROUP_B | GROUP_C) - fired)
