"""create alerts table

Revision ID: a9d0d3e797ff
Revises: e106be1e97bd
Create Date: 2026-07-13 21:36:32.481035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d0d3e797ff'
down_revision: Union[str, Sequence[str], None] = 'e106be1e97bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('event_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('time_window_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('matched_line_numbers', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('NEW', 'REVIEWING', 'ESCALATED', 'CLOSED')", name='ck_alerts_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_rule', 'alerts', ['rule'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_source_ip', 'alerts', ['source_ip'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_upload_id', 'alerts', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_upload_id', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_source_ip', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_rule', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
