"""create incidents table

Revision ID: c076a6e3cb3b
Revises: a9d0d3e797ff
Create Date: 2026-07-13 22:25:01.312325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c076a6e3cb3b'
down_revision: Union[str, Sequence[str], None] = 'a9d0d3e797ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_alert_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_incidents_priority'),
    sa.CheckConstraint("status IN ('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_alert_id'], ['alerts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_alert_id')
    )
    op.create_index('ix_incidents_assigned_user_id', 'incidents', ['assigned_user_id'], unique=False)
    op.create_index('ix_incidents_created_at', 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_priority', 'incidents', ['priority'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_priority', table_name='incidents')
    op.drop_index('ix_incidents_created_at', table_name='incidents')
    op.drop_index('ix_incidents_assigned_user_id', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
