"""create logs table

Revision ID: e106be1e97bd
Revises: 470786ae672a
Create Date: 2026-07-13 00:47:07.185947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e106be1e97bd'
down_revision: Union[str, Sequence[str], None] = '470786ae672a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), server_default=sa.text("'security_event'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'line_number', name='uq_logs_upload_line_number')
    )
    op.create_index('ix_logs_event_timestamp', 'logs', ['event_timestamp'], unique=False)
    op.create_index('ix_logs_event_type', 'logs', ['event_type'], unique=False)
    op.create_index('ix_logs_ip_address', 'logs', ['ip_address'], unique=False)
    op.create_index('ix_logs_status', 'logs', ['status'], unique=False)
    op.create_index('ix_logs_upload_id', 'logs', ['upload_id'], unique=False)
    op.create_index('ix_logs_username', 'logs', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_username', table_name='logs')
    op.drop_index('ix_logs_upload_id', table_name='logs')
    op.drop_index('ix_logs_status', table_name='logs')
    op.drop_index('ix_logs_ip_address', table_name='logs')
    op.drop_index('ix_logs_event_type', table_name='logs')
    op.drop_index('ix_logs_event_timestamp', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
